apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "guto-app.labels" . | nindent 4 }}
  {{- if .Values.secret.name }}
  name: {{ .Values.secret.name }}
  {{- else }}
  name: {{ include "guto-app.fullname" . }}
  {{- end }}
type: Opaque
data: 
{{- range $key, $val := .Values.secret.data  }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}